version: 2
updates:
  # R dependencies
  - package-ecosystem: "r"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "r"
    commit-message:
      prefix: "chore(deps-r)"
    reviewers:
      - "diogoribeiro7"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps-actions)"
    reviewers:
      - "diogoribeiro7"
